import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/root/Header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='select-none'>
          <Header />
        </div>
        <div className='bg-zinc-400 overflow-auto h-[calc(100vh-80px)] select-none'>
          {children}
        </div>
      </body>
    </html>
  )
}
