import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/root/Header/Header'
import { Toaster } from '@/components/ui/sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='select-none'>
          <Header />
        </div>
        <div className='p-2 bg-gradient-to-t from-zinc-300 to-zinc-400'>
          <div className='bg-zinc-100 overflow-auto h-[calc(100vh-80px)] select-none rounded'>
            {children}
          </div>
        </div>
        <div>
          <Toaster />
        </div>
      </body>
    </html>
  )
}
